MODULE BASIC_DATA
IMPLICIT NONE

! GLOBLE CONSTANTS
INTEGER(4), PARAMETER::  INT_KIND  = SELECTED_INT_KIND(8)
INTEGER(4), PARAMETER::  REAL_KIND = SELECTED_REAL_KIND(P=15)
INTEGER(4), PARAMETER::  REAL_EPS  = EPSILON(1.0_REAL_KIND)  ! THE MINIMUM DIFFERENCE BETWEEN TWO REAL NUMBERS

! BASIC STRUCTURES
TYPE MATERIAL
   CHARACTER(32)::  MATERIAL_TYPE = ' '
   ! MECHANICAL
   ! ANISOTROPIC
   REAL(REAL_KIND):: E11 = 0.0   ! E FOR ISOTROPIC MATERIAL
   REAL(REAL_KIND):: E22 = 0.0
   REAL(REAL_KIND):: E33 = 0.0
   REAL(REAL_KIND):: G12 = 0.0
   REAL(REAL_KIND):: G23 = 0.0
   REAL(REAL_KIND):: G31 = 0.0
   REAL(REAL_KIND):: V12 = 0.0   ! V FOR ISOTROPIC MATERIAL
   REAL(REAL_KIND):: V23 = 0.0
   REAL(REAL_KIND):: V31 = 0.0   
   REAL(REAL_KIND):: ANGLE = 0.0   
   REAL(REAL_KIND):: DENSITY = 0.0
   
   ! THERMAL
   REAL(REAL_KIND):: K1 = 0.0    ! K FOR ISOTROPIC MATERIAL
   REAL(REAL_KIND):: K2 = 0.0
   REAL(REAL_KIND):: K3 = 0.0
   REAL(REAL_KIND):: ALFA1 = 0.0 ! ALFA FOR ISOTROPIC MATERIAL
   REAL(REAL_KIND):: ALFA2 = 0.0
   REAL(REAL_KIND):: ALFA3 = 0.0
   REAL(REAL_KIND):: C = 0.0
   REAL(REAL_KIND):: EMISSIVITY = 0.0
   REAL(REAL_KIND):: ABSORPTIVITY = 0.0
   REAL(REAL_KIND):: HGEN_RATE = 0.0 ! HEAT GENERATION RATE
END TYPE

TYPE GEOMETRY
   CHARACTER(32)::  GEOMETRY_TYPE = ' '
   REAL(REAL_KIND):: A = 0.0     ! WIDTH OR OUTER RADIUS
   REAL(REAL_KIND):: B = 0.0     ! HIGHT OR INNER RADIUS
   REAL(REAL_KIND):: THICKNESS = 0.0
   REAL(REAL_KIND):: IY = 0.0
   REAL(REAL_KIND):: IZ = 0.0
   REAL(REAL_KIND):: CY = 0.0
   REAL(REAL_KIND):: CZ = 0.0
   REAL(REAL_KIND):: THETA = 0.0
END TYPE

TYPE ELEMENT
   CHARACTER(32)::     ELEMENT_TYPE = ' '
   INTEGER(INT_KIND):: NUM_NODE = 0
   INTEGER(INT_KIND):: MATERIAL = 0
   INTEGER(INT_KIND):: GEOMETRY = 0
   INTEGER(INT_KIND), ALLOCATABLE::  NODE(:)
END TYPE

! GLOBLE DATA
CHARACTER(32)     PROJECT_NAME
INTEGER(INT_KIND) NUM_NODE
INTEGER(INT_KIND) NUM_MATERIAL
INTEGER(INT_KIND) NUM_GEOMETRY
INTEGER(INT_KIND) NUM_ELEMENT
REAL(REAL_KIND), ALLOCATABLE::  XYZ(:,:)
TYPE(MATERIAL), ALLOCATABLE::  MATERIALS(:)
TYPE(GEOMETRY), ALLOCATABLE::  GEOMETRIES(:)
TYPE(ELEMENT), ALLOCATABLE::   ELEMENTS(:)

! FILE HANDLES
INTEGER(INT_KIND), PARAMETER:: CONTROL  = 1
INTEGER(INT_KIND), PARAMETER:: BOUNDARY = 2
INTEGER(INT_KIND), PARAMETER:: LOG      = 3
INTEGER(INT_KIND), PARAMETER:: OUT      = 4

! INTERFACES
INTERFACE OPERATOR (.EQ.)
   MODULE PROCEDURE ELEMENT_EQ
END INTERFACE

CONTAINS
   PURE FUNCTION ELEMENT_EQ(E1, E2)
   IMPLICIT NONE
   TYPE(ELEMENT), INTENT(IN):: E1, E2
   LOGICAL ELEMENT_EQ
   
   ELEMENT_EQ = E1%ELEMENT_TYPE .EQ. E2%ELEMENT_TYPE .AND.&
                E1%NUM_NODE     .EQ. E2%NUM_NODE     .AND.&
                E1%MATERIAL     .EQ. E2%MATERIAL     .AND.&
                E1%GEOMETRY     .EQ. E2%GEOMETRY     .AND.&
                ALL(E1%NODE .EQ. E2%NODE)

   END FUNCTION
   
   !----------------------------------------------------------   
   FUNCTION REMOVE_BLANK_TABLE(STRING)
   IMPLICIT NONE
   CHARACTER(*), INTENT(IN)::  STRING
   CHARACTER(LEN(STRING))       REMOVE_BLANK_TABLE
   INTEGER(INT_KIND)            ASCII
   INTEGER(INT_KIND)            TAIL

   ! REMOVE TAIL BLANKS
   REMOVE_BLANK_TABLE = ADJUSTR(STRING)
   
   ! REMOVE TAIL TABLES
   TAIL  = LEN(REMOVE_BLANK_TABLE)
   ASCII = ICHAR(REMOVE_BLANK_TABLE(TAIL:TAIL))
   DO WHILE(ASCII .EQ. 9)
      REMOVE_BLANK_TABLE(TAIL:TAIL) = ' '
      REMOVE_BLANK_TABLE = ADJUSTR(REMOVE_BLANK_TABLE)
      ASCII = ICHAR(REMOVE_BLANK_TABLE(TAIL:TAIL))
   ENDDO
   
   ! REMOVE LEADING BLANKS
   REMOVE_BLANK_TABLE = ADJUSTL(REMOVE_BLANK_TABLE)
            
   ! REMOVE LEADING TABLES
   ASCII = ICHAR(REMOVE_BLANK_TABLE(1:1))
   DO WHILE(ASCII .EQ. 9)
      REMOVE_BLANK_TABLE(1:1) = ' '
      REMOVE_BLANK_TABLE = ADJUSTL(REMOVE_BLANK_TABLE)
      ASCII = ICHAR(REMOVE_BLANK_TABLE(1:1))
   ENDDO
   
   END FUNCTION
   
   !----------------------------------------------------------
   FUNCTION REMOVE_FIRSTWORD(STRING)
   IMPLICIT NONE
   CHARACTER(*), INTENT(IN)::  STRING
   CHARACTER(LEN(STRING))       REMOVE_FIRSTWORD
   INTEGER(INT_KIND)            BLANK
   INTEGER(INT_KIND)            TABLE
   
   REMOVE_FIRSTWORD = REMOVE_BLANK_TABLE(STRING)
   BLANK = INDEX(REMOVE_FIRSTWORD, ' ')
   TABLE = INDEX(REMOVE_FIRSTWORD, CHAR(9))
   IF(BLANK .EQ. 0) BLANK = LEN(REMOVE_FIRSTWORD)
   IF(TABLE .EQ. 0) TABLE = LEN(REMOVE_FIRSTWORD)
   REMOVE_FIRSTWORD(1:MIN(BLANK,TABLE)) = ' '
   REMOVE_FIRSTWORD = REMOVE_BLANK_TABLE(REMOVE_FIRSTWORD)
      
   END FUNCTION
   
   !----------------------------------------------------------
   CHARACTER(128) FUNCTION GET_COMMAND(FILE)
   IMPLICIT NONE
   INTEGER(INT_KIND), INTENT(IN):: FILE

   ! BYPASS '!' AND BLANKS
   DO
      READ(FILE, '(A128)') GET_COMMAND
      
      ! DELETE LEADING BLANKS
      GET_COMMAND = REMOVE_BLANK_TABLE(GET_COMMAND)     
                    
      IF(GET_COMMAND(1:1) .NE. '!' .AND. GET_COMMAND(1:1) .NE. ' ') EXIT
   END DO
   END FUNCTION
     
END MODULE