python -c "from test_0 import test_prime; test_prime(1,False)"
python -c "from test_0 import test_prime; test_prime(8,False)"
python -c "from test_0 import test_prime; test_prime(25,False)"
python -c "from test_0 import test_prime; test_prime(3,True)"
python -c "from test_0 import test_prime; test_prime(7,True)"
python -c "from test_0 import test_prime; test_prime(10,False)"
python -c "from test_0 import test_prime; test_prime(12,False)"
python -c "from test_0 import test_prime; test_prime(99,False)"